spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/litanghis
    username: root
    password: 1209304680
  data:
    redis:
      host: 192.168.23.128
      port: 6379
      database: 4
      password: root
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 10s
mybatis:
  configuration:
    map-underscore-to-camel-case: true

